buttons:
  launch_torpedo1: 2
  launch_torpedo2: 1
  drop_ball: 0
  z_axis_pos:
    index: 5
    gain: 0.4
  z_axis_neg:
    index: 4
    gain: 0.4
  # ROV mode buttons (when rov=1)
  rov_pitch_pos: 0
  rov_pitch_neg: 3
  rov_roll_pos: 1
  rov_roll_neg: 2
  reset_orientation: 10

axes:
  x_axis:
    index: 1
    gain: 0.4
  y_axis:
    index: 0
    gain: 0.4
  yaw_axis:
    index: 3
    gain: 0.5
  # ROV mode gains
  rov_pitch_gain: 0.5
  rov_roll_gain: 0.5
