model:
  mass_inertia_matrix:
    - [29.8419, 0, 0, 0, -1.5306, -0.4401]
    - [0, 29.8419, 0, 1.5306, 0, -0.6235]
    - [0, 0, 29.8419, 0.4401, 0.6235, 0]
    - [0, 1.5306, 0.4401, 0.9430, -0.0317, 0.1290]
    - [-1.5306, 0, 0.6235, -0.0317, 2.1200, -0.1070]
    - [-0.4401, -0.6235, 0, 0.1290, -0.1070, 2.1800]

  linear_damping_matrix:
    - [45.8, 0, 0, 0, 0, 0]
    - [0, 42.37, 0, 0, 0, 0]
    - [0, 0, 89.2, 0, 0, 0]
    - [0, 0, 0, 0.0, 0, 0]
    - [0, 0, 0, 0, 0.0, 0]
    - [0, 0, 0, 0, 0, 5.646]

  quadratic_damping_matrix:
    - [141.9, 0, 0, 0, 0, 0]
    - [0, 221.7, 0, 0, 0, 0]
    - [0, 0, 136.16, 0, 0, 0]
    - [0, 0, 0, 0.0, 0, 0]
    - [0, 0, 0, 0, 0.0, 0]
    - [0, 0, 0, 0, 0, 2.608]

# Format: [x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw]
#kp: [0.0, 0.0, 1.5, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 5.0, 0.0, 1.0]
#ki: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
#kd: [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0]

kp: [1.0, 1.0, 0.8, -1.0, -0.5, 2.0, 1.0, 1.0, 1.0, -10.0, -10.0, 6.0]
ki: [0.0, 0.0, 0.0003, -0.003, -0.003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0002]
kd: [0.7, 0.7, 1.2, -0.1, -0.007, 0.3, 1.0, 1.0, 1.0, -1.0, -1.0, 10.0]
integral_clamp_limits: [0.0, 0.0, 100.0, 100.0, 100.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 100.0]

max_velocity: [0.6, 0.6, 0.6, 0.4, 0.4, 0.4]

max_thrust: 60.0 # N
min_thrust: 0.5 # N
coeffs_ccw: [12.292935764557399, -3.0745135927968605, -1.0664649834600253, 181.68212348405177, 36.69456713973092, 1151.1307183400536]
coeffs_cw: [-7.65890867108129, -2.272619267631361, 1.5070809906898863, 140.79738360070297, -50.325593642656244, 1954.5975713257544]
mapping: [4, 0, 2, 6, 7, 3, 1, 5]
