---
model:
  mass_inertia_matrix:
    - [27.0, 0, 0, 0, 0, 0]
    - [0, 27.0, 0, 0, 0, 0]
    - [0, 0, 27.0, 0, 0, 0]
    - [0, 0, 0, 0.75, 0, 0]
    - [0, 0, 0, 0, 2.245, 0]
    - [0, 0, 0, 0, 0, 2.116]

  linear_damping_matrix:
    - [30.1481, 0, 0, 0, 0, 0]
    - [0, 31.4748, 0, 0, 0, 0]
    - [0, 0, 89.2, 0, 0, 0]
    - [0, 0, 0, 0.0, 0, 0]
    - [0, 0, 0, 0, 0.0, 0]
    - [0, 0, 0, 0, 0, 1.87816]

  quadratic_damping_matrix:
    - [77.0139, 0, 0, 0, 0, 0]
    - [0, 155.237, 0, 0, 0, 0]
    - [0, 0, 136.16, 0, 0, 0]
    - [0, 0, 0, 0.0, 0, 0]
    - [0, 0, 0, 0, 0.0, 0]
    - [0, 0, 0, 0, 0, 7.98053]

  # MPC Model Parameters
  m: 27.0
  rg: [0.0, 0.0, 0.0]
  rb: [0.0, 0.0, 0.2]
  I_g: [0.75, 2.245, 2.116]
  MA: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  DL: [30.1481, 31.4748, 89.2, 0.0, 0.0, 1.87816]
  DQ: [77.0139, 155.237, 136.16, 0.0, 0.0, 7.98053]
  W: 264.87
  B: 264.87

mpc:
  N: 40
  Q_pos: [100, 100, 400]
  Q_vel: [11, 11, 11, 11, 11, 11]
  Q_ori: 150.0
  R_tau: [0.03, 0.03, 0.05, 0.02, 0.02, 0.02]
  QN_pos: [500.0, 500.0, 2000.0]
  QN_vel: [55.0, 55.0, 55.0, 55.0, 55.0, 55.0]
  QN_ori: 600.0
  tau_min: [-60, -60, -60, -60, -60, -60]
  tau_max: [60, 60, 60, 60, 60, 60]
  nu_min: [-1, -1, -1, -0.5, -0.5, -0.5]
  nu_max: [1, 1, 1, 0.5, 0.5, 0.5]

# Format: [x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw]
#kp: [0.0, 0.0, 1.5, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 5.0, 0.0, 1.0]
#ki: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
#kd: [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0]

kp: [0.0, 0.0, 0.8, -1.0, -0.5, 2.0, 1.0, 1.0, 1.0, -10.0, -10.0, 6.0]
ki: [0.0, 0.0, 0.0003, -0.003, -0.003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0002]
kd: [0.0, 0.0, 1.2, -0.1, -0.007, 0.3, 1.0, 1.0, 1.0, -1.0, -1.0, 10.0]
integral_clamp_limits: [0.0, 0.0, 100.0, 100.0, 100.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 100.0]

max_thrust: 60.0 # N
min_thrust: 0.5 # N
coeffs_ccw: [12.292935764557399, -3.0745135927968605, -1.0664649834600253, 181.68212348405177, 36.69456713973092, 1151.1307183400536]
coeffs_cw: [-7.65890867108129, -2.272619267631361, 1.5070809906898863, 140.79738360070297, -50.325593642656244, 1954.5975713257544]
mapping: [4, 0, 2, 6, 7, 3, 1, 5]
