services:
  auv-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    image: auv-dev:latest
    container_name: auv-dev
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - TERM=xterm-256color
      - ROS_MASTER_URI=${ROS_MASTER_URI}
      - ROS_IP=${ROS_IP}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ..:/auv_ws/src/auv_software:rw
      - auv_root:/root
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    command: zsh

volumes:
  auv_root:
