cam_front:
  width: 640
  height: 480
  fps: 30
  device: /dev/auv_cam_front

  image_width: 640
  image_height: 480
  camera_name: cam_front
  camera_matrix:
    rows: 3
    cols: 3
    data: [713.243907, 0.0, 298.628312, 0.0, 730.635954, 165.631099, 0.0, 0.0, 1.0]
  distortion_model: plumb_bob
  distortion_coefficients:
    rows: 1
    cols: 5
    data: [0.047708, 0.048848, -0.034526, -0.000153, 0.0]
  rectification_matrix:
    rows: 3
    cols: 3
    data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
  projection_matrix:
    rows: 3
    cols: 4
    data: [732.617981, 0.0, 298.604817, 0.0, 0.0, 729.010986, 154.053329, 0.0, 0.0, 0.0, 1.0, 0.0]

cam_bottom_old:
  width: 640
  height: 480
  fps: 30
  device: /dev/auv_cam_bottom

  image_width: 640
  image_height: 480
  camera_name: cam_bottom
  camera_matrix:
    rows: 3
    cols: 3
    data: [998.599439, 0.0, 265.425260, 0.0, 979.419592, 240.402775, 0.0, 0.0, 1.0]
  distortion_model: plumb_bob
  distortion_coefficients:
    rows: 1
    cols: 5
    data: [0.869643, -1.060488, -0.007736, -0.062698, 0.0]
  rectification_matrix:
    rows: 3
    cols: 3
    data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
  projection_matrix:
    rows: 3
    cols: 4
    data: [1081.186890, 0.0, 252.365375, 0.0, 0.0, 1083.032104, 238.487351, 0.0, 0.0, 0.0, 1.0, 0.0]

cam_torpedo:
  width: 800
  height: 448
  fps: 30

  image_width: 800
  image_height: 448
  camera_name: cam_torpedo
  camera_matrix:
    rows: 3
    cols: 3
    data: [356.599055643449, 0.0, 410.01319747359395, 0.0, 354.9934687487455, 197.61449530601143, 0.0, 0.0, 1.0]
  distortion_model: plumb_bob
  distortion_coefficients:
    rows: 1
    cols: 5
    data: [-0.23963595157141618, 0.14183427070668228, 0.01171450897124783, -0.00038163496663176383, 0.0]
  rectification_matrix:
    rows: 3
    cols: 3
    data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
  projection_matrix:
    rows: 3
    cols: 4
    data: [365.2460632324219, 0.0, 403.44751861529585, 0.0, 0.0, 359.3122863769531, 210.59759350842796, 0.0, 0.0, 0.0, 1.0, 0.0]

cam_bottom:
  width: 1920
  height: 1080
  fps: 30
  device: /dev/auv_cam_ov2710

  image_width: 1920
  image_height: 1080
  camera_name: cam_bottom
  camera_matrix:
    rows: 3
    cols: 3
    data: [1300.278562, 0.0, 963.616380, 0.0, 1301.913143, 502.538883, 0.0, 0.0, 1.0]
  distortion_model: plumb_bob
  distortion_coefficients:
    rows: 1
    cols: 5
    data: [-0.330122, 0.135823, 0.001839, 0.000819, 0.0]
  rectification_matrix:
    rows: 3
    cols: 3
    data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
  projection_matrix:
    rows: 3
    cols: 4
    data: [1068.462402, 0.0, 967.401311, 0.0, 0.0, 1223.300049, 498.828315, 0.0, 0.0, 0.0, 1.0, 0.0]
