cam_front:
  width: 640
  height: 480
  fps: 30
  device: /dev/auv_cam_front

  image_width: 640
  image_height: 480
  camera_name: cam_front
  camera_matrix:
    rows: 3
    cols: 3
    data: [582.482268, 0.0, 304.827170, 0.0, 586.777066, 239.637541, 0.0, 0.0, 1.0]
  distortion_model: plumb_bob
  distortion_coefficients:
    rows: 1
    cols: 5
    data: [-0.037791, -0.050488, -0.001640, -0.001722, 0.0]
  rectification_matrix:
    rows: 3
    cols: 3
    data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
  projection_matrix:
    rows: 3
    cols: 4
    data: [571.519592, 0.0, 302.673145, 0.0, 0.0, 580.852783, 238.631294, 0.0, 0.0, 0.0, 1.0, 0.0]

cam_bottom_old:
  width: 640
  height: 480
  fps: 30
  device: /dev/auv_cam_bottom

  image_width: 640
  image_height: 480
  camera_name: cam_bottom
  camera_matrix:
    rows: 3
    cols: 3
    data: [998.599439, 0.0, 265.425260, 0.0, 979.419592, 240.402775, 0.0, 0.0, 1.0]
  distortion_model: plumb_bob
  distortion_coefficients:
    rows: 1
    cols: 5
    data: [0.869643, -1.060488, -0.007736, -0.062698, 0.0]
  rectification_matrix:
    rows: 3
    cols: 3
    data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
  projection_matrix:
    rows: 3
    cols: 4
    data: [1081.186890, 0.0, 252.365375, 0.0, 0.0, 1083.032104, 238.487351, 0.0, 0.0, 0.0, 1.0, 0.0]

cam_torpedo:
  width: 800
  height: 448
  fps: 30

  image_width: 800
  image_height: 448
  camera_name: cam_torpedo
  camera_matrix:
    rows: 3
    cols: 3
    data: [350.2366280790792, 0.0, 407.1044704880514, 0.0, 348.9184531000424, 201.94397632455394, 0.0, 0.0, 1.0]
  distortion_model: plumb_bob
  distortion_coefficients:
    rows: 1
    cols: 5
    data: [-0.23188286646450512, 0.11814108319974795, 0.008332880042020778, 0.00047281030464117464, 0.0]
  rectification_matrix:
    rows: 3
    cols: 3
    data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
  projection_matrix:
    rows: 3
    cols: 4
    data: [343.44927978515625, 0.0, 404.5205187438405, 0.0, 0.0, 338.4554138183594, 210.64106797577915, 0.0, 0.0, 0.0, 1.0, 0.0]

cam_bottom:
  width: 1920
  height: 1080
  fps: 30
  device: /dev/auv_cam_ov2710

  image_width: 1920
  image_height: 1080
  camera_name: cam_bottom
  camera_matrix:
    rows: 3
    cols: 3
    data: [1300.278562, 0.0, 963.616380, 0.0, 1301.913143, 502.538883, 0.0, 0.0, 1.0]
  distortion_model: plumb_bob
  distortion_coefficients:
    rows: 1
    cols: 5
    data: [-0.330122, 0.135823, 0.001839, 0.000819, 0.0]
  rectification_matrix:
    rows: 3
    cols: 3
    data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
  projection_matrix:
    rows: 3
    cols: 4
    data: [1068.462402, 0.0, 967.401311, 0.0, 0.0, 1223.300049, 498.828315, 0.0, 0.0, 0.0, 1.0, 0.0]
