obstacle_range: 20.0
raytrace_range: 30.0
# footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
footprint: [[-0.6, -0.5], [0.6, -0.5], [0.6, 0.5], [-0.6, 0.5]]
robot_radius: 0.6
# 1 width
# 2 height
min_obstacle_height: -10.0
max_obstacle_height: 10.0
inflation_radius: 1.0
cost_scaling_factor: 2.0
map_type: costmap
#observation_sources: scan
#scan: {sensor_frame: taluy/base_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

observation_sources: pointcloud
pointcloud: {sensor_frame: taluy/base_link, data_type: PointCloud, topic: pointcloud, marking: true, clearing: true}
