DWAPlannerROS:

  # Robot Configuration Parameters
  max_vel_x: 0.4
  min_vel_x: -0.4

  max_vel_y: 0.4
  min_vel_y: -0.4

  # The velocity when robot is moving in a straight line
  max_vel_trans: 0.7
  min_vel_trans: -0.7

  max_vel_theta: 0.3
  min_vel_theta: -0.3

  acc_lim_x: 2.0
  acc_lim_y: 0.0
  acc_lim_theta: 3.0
  acc_lim_trans: 5.0

  # Goal Tolerance Parametes
  xy_goal_tolerance: 1.0
  yaw_goal_tolerance: 0.4
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 2.0
  vx_samples: 10
  vy_samples: 0
  vth_samples: 20
  controller_frequency: 20.0

  # Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
  forward_point_distance: 0.325
  stop_time_buffer: 1.0
  scaling_speed: 1.0
  max_scaling_factor: 0.2

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

  # Debugging
  publish_traj_pc: true
  publish_cost_grid_pc: true
