local_costmap:
  global_frame: odom
  robot_base_frame: taluy/base_link

  update_frequency: 20.0
  publish_frequency: 20.0
  transform_tolerance: 1.0

  static_map: false
  rolling_window: true
  width: 10
  height: 10
  resolution: 0.01
  track_unknown_space: false
