reference_frame: coin_flip_rescuer
objects:
  bin:
    position:
      - 3.5664819944598314
      - 11.045706371191136
      - -2.0
    orientation:
      - 0.0
      - 0.0
      - 0.0
      - 1.0
  torpedo:
    position:
      - -4.847645429362883
      - 11.18421052631579
      - -1.5
    orientation:
      - 0.0
      - 0.0
      - 0.0
      - 1.0
  octagon:
    position:
      - -1.0041551246537423
      - 18.490304709141274
      - -1.3
    orientation:
      - 0.0
      - 0.0
      - 0.0
      - 1.0
